### ISSUE TITLE
Chapter 4 Introduction: '1s' and '0s'

### ISSUE THREAD

**Issue by fridlmue** [777arc/textbook#31]
When reading this first I got confused (I'm a not native English speaker) by the '1s', as i usually read it as 'one second'. I got it thinking about it, but it could mislead. Probably some kind of clarification could be helpful. It's not really a Issue, but I was confused reading it that way...

**Comment by 777arc** [comment]
Yeah I'll switch it back to 1's and 0's, I think 1s and 0s might be the proper technical English but it's more prone to confusion
