### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by kenfallon** [777arc/textbook#33]
Could you clarify the situation related to license please.

**Comment by 777arc** [comment]
Yep, I've been reading about CC-BY-SA-NC, seems perfect, I just want to prevent someone from being able to legally print a hard copy and sell it, since I don't want there to exist a hard copy, due to the heavy use of animations (I'll be adding even more animations over time).

**Comment by 777arc** [comment]
Oh, but there are a few figures, like this one https://pysdr.org/_images/atmospheric_attenuation.png (came from a different textbook) that I'll have to replace before I assign this license, I'll just recreate them.  I'll try to finish doing that by Feb 12 2021

**Comment by 777arc** [comment]
Done!  Turns out MATLAB had a function for getting atmospheric attenuation, so I made my own plot - https://pysdr.org/content/link_budgets.html#miscellaneous-losses
