### ISSUE TITLE
Phase Noise

### ISSUE THREAD

**Issue by DavidLutton** [777arc/textbook#34]
in [Digital Modulation](https://pysdr.org/content/digital_modulation.html#python-example) you show a QPSK constellation plot then plot with Gaussian noise.
You can demonstrate phase noise with modification of the Python example in that chapter.
```python
num_symbols = 1000

x_int = np.random.randint(0, 4, num_symbols) # 0 to 3
x_degrees = x_int*360/4.0 + 45 # 45, 135, 225, 315 degrees

phase_noise = np.random.standard_normal(len(x_degrees))/8  # generate phase noise  
x_radians = phase_noise+x_degrees*np.pi/180.0 # sin() and cos() takes in radians

x_symbols = np.cos(x_radians) + 1j*np.sin(x_radians) # this produces our QPSK complex symbols
plt.plot(np.real(x_symbols), np.imag(x_symbols), '.')
plt.grid(True)
plt.show()
```
![image](https://user-images.githubusercontent.com/1688143/107583658-26f8da00-6bf3-11eb-86d0-87aa6c744880.png)
Then plot with Gaussian noise to produce
```Python
n = (np.random.randn(num_symbols) + 1j*np.random.randn(num_symbols))/np.sqrt(2) # AWGN with unity power
noise_power = 0.01
r = x_symbols + n * np.sqrt(noise_power)
plt.plot(np.real(r), np.imag(r), '.')
plt.grid(True)
plt.show()
```
![image](https://user-images.githubusercontent.com/1688143/107583710-3d9f3100-6bf3-11eb-88a7-37d817ba8ad6.png)

Would it be suitable to add to this chapter?

**Comment by 777arc** [comment]
I went ahead and added it, I made a slight tweak by applying the phase jitter directly to r, just to make it clear where it would actually happen.  Great suggestion!
