### ISSUE TITLE
Carrier AM FM Animation

### ISSUE THREAD

**Issue by DavidLutton** [777arc/textbook#35]
in [Digital Modulation](https://pysdr.org/content/digital_modulation.html#frequency-shift-keying-fsk) you show a time domain example of Carrier, AM, FM
I have got to this point with Matplotlib
![image](https://user-images.githubusercontent.com/1688143/107589508-1863f000-6bfe-11eb-8d17-d714f1de56e5.png)
Planning to proceed with making an animation

**Comment by 777arc** [comment]
Oh!  Awesome!  I saw a similar animation on another site but didn't want to copy it =P

**Comment by 777arc** [comment]
Making it as an animated gif is best, but I can always find a way to convert it if it's not

**Comment by DavidLutton** [comment]
![waves](https://user-images.githubusercontent.com/1688143/108570270-5e5b3b00-7305-11eb-9b46-7eff43a854db.gif)

gif format seems to alias the moving lines

Formatted as webp [waves.webp.zip](https://github.com/777arc/textbook/files/6013457/waves.zip) looks cleaner when opened in browser
Most browsers can support [webp](https://caniuse.com/webp) images/animations

Comments?

**Comment by 777arc** [comment]
ooo nice!  yeah you're right, i should be able to use a webp directly.

**Comment by 777arc** [comment]
Did you want me to go ahead and stick in that webp file?  And is there source code used to generate the animation I can add to the figure-generating-scripts directory where I stuck all the other scripts?

**Comment by DavidLutton** [comment]
Not as is, one frame was being used twice. PR as #39

**Comment by DavidLutton** [comment]
Thanks for putting #39 into this textbook.
