### ISSUE TITLE
Sampling - Calculating PSD

### ISSUE THREAD

**Issue by DavidLutton** [777arc/textbook#38]
In [Sampling - Calculating PSD](https://pysdr.org/content/sampling.html#calculating-power-spectral-density)
I am taking IQ samples from a Agilent E4406A VSA, of a FM signal.
Frequency spectrum peaks are incorrectly reproduced compared to the analysers spectrum display.

This can be fixed for the IQ samples, I've got by modifying
`PSD_log = 10.0*np.log10(PSD)` 
Based on [Calculating RF Power from IQ Samples | Tektronix](https://www.tek.com/blog/calculating-rf-power-iq-samples).
To
`PSD_log = 10.0*np.log10(10*PSD)` 
Works for me, is this scaled differently from a PlutoSDR?

**Comment by DavidLutton** [comment]
Let me check my working tomorrow, I might have done something out of order in JupyterLab

**Comment by 777arc** [comment]
Right, so I didn't make it clear, but the Pluto and other low-cost SDRs aren't able to give you absolute power levels, like their sample value X doesn't correspond to an exact level in dBm or anything, and even if it did your antenna gain would throw it off probably.  So all we can say is that it's in dB, like it's essentially dBm + some unknown offset.  At least that's the way I've always dealt with it.  You can calibrate these SDRs but it's a whole process and it will change over freq, temperature, and antenna.

**Comment by 777arc** [comment]
It might also have to do with how we scaled the FFT, like dividing by sample rate or FFT size.

**Comment by 777arc** [comment]
Closing this for now, I don't think the 10*PSD is a standard by any means, and certainly not necessary for doing anything with uncalibrated SDRs.
