### ISSUE TITLE
Sawtooth Sine Wave Summation Discrepancy?

### ISSUE THREAD

**Issue by dmstuffer** [777arc/textbook#4]
In the Frequency Distribution chapter, the image fourier_series_triangle.gif demonstrates how the sawtooth wave appears when 10 waves are summed up. I assume it is 10 because the animation finishes with n = 10. The paragraph describing it indicates sawtooth wave is made by combining up to five waves. Should the text be changed to reflect the number 10 instead of five?

<img width="646" alt="five vs ten" src="https://user-images.githubusercontent.com/17556350/95926388-c9a66680-0d81-11eb-9518-8cbd2d029ef5.png">

**Comment by 777arc** [comment]
Ah, originally I had used an animated gif I found online, but then I created my own and went up to 10 instead of 5.  Thanks for catching that!
