### ISSUE TITLE
Blue line in figure almost invisible 

### ISSUE THREAD

**Issue by warnes** [777arc/textbook#48]
In https://pysdr.org/content/sampling.html#quadrature-sampling the I,Q,I+Q animation generated from https://raw.githubusercontent.com/777arc/textbook/master/figure-generating-scripts/sin_plus_cos.py has three lines, `I*cos()` is red,  `Q*sin()` is blue, and `I*cos() + Q*sin()` is red.  

On my display, the blue line is almost invisible on the black background:
![image](https://user-images.githubusercontent.com/6144863/152322372-17744157-a3f8-469d-a79d-ea93e50f05c4.png)

This can be corrected by either replacing the blue line with a brighter color, e.g. cyan, or by increasing the line width.

To changing the color to cyan change the pen color on line 42:
```
self.curve_Q = self.plot.plot(pen='b', name="Q*sin()")
```
to
```
self.curve_Q = self.plot.plot(pen='c', name="Q*sin()")
```

**Comment by 777arc** [comment]
Thanks for the suggestion!  I spent some time improving that graphic, I made it have a white background so that it better matches the textbook itself, check it out https://pysdr.org/_images/IQ3.gif

**Comment by warnes** [comment]
Much nicer!
