### ISSUE TITLE
Add section for bladeRF

### ISSUE THREAD

**Issue by warnes** [777arc/textbook#49]
Please add a section for Nuand's bladeRF similar to those for the PlutoSDR and the USRP.

**Comment by 777arc** [comment]
Sorry I can't cover all the common SDRs, but if someone else wants to create it I'll gladly include it and give credit to the author.  Honestly if I were to create another one, I would start with RTL-SDR, as it allows someone totally new to SDR to get started for only $20.  BladeRFs are great, as well as HackRF, LimeSDR, Fairwaves XTRX, and SDRplay, all great SDRs with different pros/cons.

**Comment by warnes** [comment]
Makes sense.  I may work through one of the two existing examples customizing it to the bladeRF.
