### ISSUE TITLE
[Mnor] Visual glitch in figure

### ISSUE THREAD

**Issue by warnes** [777arc/textbook#50]
The figure https://pysdr.org/_images/fft_signal_order.png has a glitch in the plot on the right.

`
![fft_signal_order](https://user-images.githubusercontent.com/6144863/155857766-a4274bb6-00a6-4620-b180-1915aaad1c71.png)
<img width="371" alt="Screen Shot 2022-02-26 at 3 13 08 PM" src="https://user-images.githubusercontent.com/6144863/155857770-d09cb788-6fb5-4ae9-8bdf-6ee0d826616f.png">
`

**Comment by 777arc** [comment]
Ah, yeah I keep meaning to create a python script to generate a vector graphic replacement for that one, but for now I just tweaked the png (still a tiny bit glitchy tho), should be live if you refresh cache, ty!

**Comment by warnes** [comment]
Wow, you respond quickly!!

:smile_cat:
