### ISSUE TITLE
Explaination needed for max_freq.svg

### ISSUE THREAD

**Issue by warnes** [777arc/textbook#51]
In the Nyquist sampling section, you provide a frequency domain plot and indicate the location of f_max.  However, this plot is not self-explanatory.

For instance, it would be helpful for the viewer to be informed that the high magnitudes at the left side of the plot correspond to signals, while the low magnitude values are the right correspond to noise.

This fact is implied, and may not be clear to many readers.

It would also probably be helpful to put a label on the y-axis, e.g. 'Magnitude'.

**Comment by 777arc** [comment]
Great suggestion, ty! What do you think about this- https://pysdr.org/_images/max_freq.svg

**Comment by warnes** [comment]
Looks good.
