### ISSUE TITLE
"Downconversion" used but not explained in Recieved Architectures

### ISSUE THREAD

**Issue by warnes** [777arc/textbook#52]
Also, the receiver diagrams don't contain a frequency down-converter, and don't explain what an LNA is.

**Comment by 777arc** [comment]
Agreed about LNA, I'll fix that.

Nice catch about downconversion, it's explained in the next section and I think when I rearranged things I missed that, I'll just swap the two sections.  

I'm not quite sure what you mean by no downconverter, the direct sampling doesn't have a downconverter as that's the whole point of direct sampling, with direct conversion the LO is what acts as the downconverter, so you go straight from RF to baseband.  Then in superhet the LO downconverts from RF to IF.  The 2nd and 3rd can be combined to form a superhet that brings you to baseband, like the more expensive SDRs, but I didn't want to complicate things.  I might be missing something, although I just skimmed http://rfic.eecs.berkeley.edu/~niknejad/ee242/pdf/eecs242_lect3_rxarch.pdf and I think it's pretty similar.

**Comment by warnes** [comment]
In the section "Receiver Architectures" (https://pysdr.org/content/sampling.html#receiver-architectures), you state 

> "The figure in the “Receiver Side” section demonstrates how the input signal is downconverted and split into I and Q." 

You state that Direct Sampling doesn't do any downconversion, but you don't explain how the downconversion does happens for either Direct Conversion or Superheterodyne.

The user is left to wonder whether the LNA is performing the downconversion, or if multiplying the input signal by the local oscillator (LO) is performing the downconversion, or if something else is happening.

**Comment by 777arc** [comment]
Oh ok I see what I left out, thanks for providing more details.  I added a few sentences towards the end of the Carrier and Downconversion section to help clarify.
