### ISSUE TITLE
Syntax error in Real vs Complex Filters

### ISSUE THREAD

**Issue by warnes** [777arc/textbook#53]
At least for Python 3.9.3 and Matplotlib 3.3.4, the command for setting the x-label is incorrect.  In
```python
plt.subplot(122)
plt.plot(w, H, '.-')
plt.xlabel('Frequency [Hz]')
plt.show()
```
the x-label should be set via assignment, rather than a function call:
```python
plt.subplot(122)
plt.plot(w, H, '.-')
plt.xlabel = 'Frequency [Hz]'
plt.show()
```

**Comment by 777arc** [comment]
I don't believe so, check doc screenshots below from 3.3.4, this is the first time I've heard of it not working as a function call

![Screenshot from 2022-02-26 18-31-41](https://user-images.githubusercontent.com/5722532/155862255-a9bc1230-ace2-4cf9-98b4-6084a5cbc2cd.png)

![Screenshot from 2022-02-26 18-31-58](https://user-images.githubusercontent.com/5722532/155862257-e6727a36-c702-418d-904b-c016f7c60374.png)

**Comment by warnes** [comment]
On Ubuntu 20.10:

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/6144863/155862390-edcb0c52-43d5-4914-954e-549aafe5f288.png">

and 

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/6144863/155862407-522d5d98-7af2-486f-a639-ffd36ad32f3c.png">

**Comment by 777arc** [comment]
Ohhhh derp it's because I'm using subplot, when subplot is used it has to go like this:

fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_xlabel('blah')

Nice catch!

**Comment by 777arc** [comment]
fixed, to get rid of confusion and complexity I just removed subplots from the 2 spots in the textbook that used them, folks can always google around to make their matplotlib look fancier anyway =P

**Comment by warnes** [comment]
😁
