### ISSUE TITLE
The `sinc` function is used without introduction

### ISSUE THREAD

**Issue by warnes** [777arc/textbook#56]
In the implementation of the root-raised cosine filter, the `sinc` function is used without introduction.  I, and probably other folks from outside of EE, haven't encountered this function previously, so it is probably worth introducing it, or at least providing a link to the [wikipedia page](https://en.wikipedia.org/wiki/Sinc_function) that does.

**Comment by 777arc** [comment]
mmm good point, ill add this link in, ty!
