### ISSUE TITLE
Request: loopback example 

### ISSUE THREAD

**Issue by warnes** [777arc/textbook#59]
I would love to see a loopback example that includes:
1. Reading input data
2. Generate TX stream
3. Simulate Channel
4. Receive & process RX stream
5. Compute BER

**Comment by 777arc** [comment]
Interesting idea, the sync chapter could probably be made into a full loopback example without a ton of additional code added, what do you think of that?

**Comment by warnes** [comment]
That would be a nice enhancement, especially for me because my goal is to build a full P2P system...
