### ISSUE TITLE
Request: NOAA HRPT Decoding

### ISSUE THREAD

**Issue by zeke800** [777arc/textbook#66]
Just as an idea - would it be possible to make a chapter on HRPT decoding? I have many IQ recordings and can supply one in case. 

Thank you so much!

**Comment by 777arc** [comment]
So pretty much converting https://github.com/altillimity/SatDump to python? =).  It's a continuous stream of BPSK I believe, not unlike RDS which there's already a chapter on, I feel like something that would involve having to detect the start of packets, and/or involve OFDM, would lead to more unique topics being covered between the existing RDS chapter and the next end-to-end one I make.

**Comment by zeke800** [comment]
Thank you so much for responding! Haha yes - there are already decoders, but I've always wondered how it does it in the background. Unfortunately, other than the NOAA KLM guide (which is quite complex for me to read), there are virtually zero explanations on this kind of thing (packets, headers, randomizing, etc.).

**Comment by radio-satellites** [comment]
@777arc @zeke800 I wrote something, it doesn't work that much yet but still something!!
https://github.com/radio-satellites/python-hrpt
