### ISSUE TITLE
xaxis Hz or kHz

### ISSUE THREAD

**Issue by gardintrapp** [777arc/textbook#7]
In chaper 8 Real vs. Complex Filters

Here the label for the xaxis says 'Frequency [kHz]', but
sample_rate = 32000 # Hz
w = np.linspace(-sample_rate/2, sample_rate/2, len(H)) # x axis
indicates that it should be 'Frequency in [Hz]'.
The plot generated from the code and the one in the book are different.

**Comment by 777arc** [comment]
ah, nice catch, fixing now
