### ISSUE TITLE
Expand the Differential modulation section

### ISSUE THREAD

**Issue by jdemel** [777arc/textbook#73]
I discussed Differential Modulation in this GR issue: https://github.com/gnuradio/gnuradio/issues/6074

There is the [PySDR differential coding](https://pysdr.org/content/digital_modulation.html#differential-coding) section that introduces this concept.
However, at least in the GR context it'd be great to expand that section. Especially the DQPSK example. I have a few suggestions.
1. Rename the section to "Differential Modulation". The term modulation helps to keep in mind that this is about symbols and not about bits.
2. Add a figure that illustrates how data is actually conveyed. Thus, the figure shows which transition between symbols carries which bit label.
3. Expand the DQPSK example with a demodulator to show how differential modulation may be an advantage.

I know this is quite a wishlist. Would these suggestions fit into the book?

**Comment by 777arc** [comment]
Excellent suggestion and I think it would fit really well.  Do you know of any good examples of #2 I can use for inspiration, when I create my own?

**Comment by jesseaster** [comment]
I also hit a snag trying to comprehend this section. I found this explanation to be helpful [here](http://www.ece.iit.edu/~biitcomm/research/references/Other/Tutorials%20in%20Communications%20Engineering/TUTORIAL%202%20-%20Differential%20Encoding.pdf) 

I'm working on a pull request that will have a figure showing the encoding and decoding for starting with a 1 and a 0 to show how they both decode to the same starting symbols.

**Comment by jdemel** [comment]
Actually, I don't know of any really good figures. 
For DQPSK, I'd create 4 constellation plots with rounded arrows to the next constellation point with the corresponding bit sequence. 4 constellation plots because of the 4 different starting points.

@jesseaster I had a look at the PDF in your link. Thanks for that.
One of the last sections claims
>  Differentially Encoded data sequences have a slightly superior error performance

This might be true in a specific scenario (bit sequences) but it is false in case of DPSK compared to PSK.

My suggestion here is to expand on DPSK. The linked PDF is a good reference to point out that there are differences.

**Comment by jesseaster-biomason** [comment]
Here is a figure showing binary differential coding. #74 
I don't know how differential coding works when the symbols have multiple bits.
