### ISSUE TITLE
time-scaling.svg issue

### ISSUE THREAD

**Issue by versd** [777arc/textbook#78]
As the title says, in the frequency domain chapter the image 'time-scaling.svg' is missing information.  As far as I can tell the commit that caused it is https://github.com/777arc/textbook/commit/47341e4f2b95383202d583353ffdfaa2650e29f7
Deleting the background as well as the signal.

![time-scaling](https://user-images.githubusercontent.com/7857163/205872840-18c42f13-f450-4e50-ba2f-8945abdc2ced.svg)

**Comment by 777arc** [comment]
Ah nice catch!  Looked fine in inkscape but svg got screwed up, fixing now
