### ISSUE TITLE
question about resolution in the frequency domain in character 2 Frequency Domain

### ISSUE THREAD

**Issue by chencjiajy** [777arc/textbook#80]
There are two description about resolution in this character
> Because the output is in the frequency domain, the span of the x-axis is based on the sample rate, which we will cover next chapter. When we use more samples for the input vector, we get a better resolution in the frequency domain (in addition to processing more samples at once). 

> Regarding the frequency interval, each bin corresponds to `f_s/N` Hz, i.e., feeding in more samples to each FFT will lead to more granular resolution in your output.

in my understanding, for period signal, the frequency interval always the same,   `N` changes when `f_s` changes , for example, 50Hz frequency signal, if the sample rate is 6000, N is 120, when sample rate is 5000, N would be 100.   
so how to understand "feeding in more samples to each FFT will lead to more granular resolution in your output" ?

**Comment by versd** [comment]
So there are several aspects you need to keep separate. There is the signal itself that you’re trying to measure with a certain frequency content. If that signal happens to be a single periodic function then it would also have a frequency and period.

Next there is the measuring itself. This happens at a frequency too, the sample rate.  The sample rate determines the bandwidth of the output. The resolution of the output, i.e. the number of bins, is determined by the last parameter: how long do we measure the signal for? The longer you measure, the more samples you have and the more information you acquire about the signal, hence the higher resolution. So N in your story refers to the number of samples that you have taken.

**Comment by 777arc** [comment]
> So there are several aspects you need to keep separate. There is the signal itself that you’re trying to measure with a certain frequency content. If that signal happens to be a single periodic function then it would also have a frequency and period.
> 
> Next there is the measuring itself. This happens at a frequency too, the sample rate. The sample rate determines the bandwidth of the output. The resolution of the output, i.e. the number of bins, is determined by the last parameter: how long do we measure the signal for? The longer you measure, the more samples you have and the more information you acquire about the signal, hence the higher resolution. So N in your story refers to the number of samples that you have taken.

Great explanation!  Ultimately, you choose N, it's the size of the FFT, i.e. how many samples you perform an FFT on.  You might record 1 million samples but then take FFTs that are all N=1024 size, so about 1000 FFTs total.  You can average them all to get 1 smooth FFT, or stack them to create a spectrogram.

**Comment by chencjiajy** [comment]
> > So there are several aspects you need to keep separate. There is the signal itself that you’re trying to measure with a certain frequency content. If that signal happens to be a single periodic function then it would also have a frequency and period.
> > Next there is the measuring itself. This happens at a frequency too, the sample rate. The sample rate determines the bandwidth of the output. The resolution of the output, i.e. the number of bins, is determined by the last parameter: how long do we measure the signal for? The longer you measure, the more samples you have and the more information you acquire about the signal, hence the higher resolution. So N in your story refers to the number of samples that you have taken.
> 
> Great explanation! Ultimately, you choose N, it's the size of the FFT, i.e. how many samples you perform an FFT on. You might record 1 million samples but then take FFTs that are all N=1024 size, so about 1000 FFTs total. You can average them all to get 1 smooth FFT, or stack them to create a spectrogram.

sorry, I know how you mean literally,  spectrogram could shows how frequency very over time, but I still confused.  I thought N is how many sample record in exactly one period of a period signal, so `N=f_s/f_0`,  where `f_s` is the sample rate and `f_0` is frequency of period signal。 if there is a 50Hz frequency  period of signal,  if the sample rate is 5000 Hz and I record 5000 samples, N=100, about 50 FFTs total;  if the sample rate is 6000 Hz and I record 6000 samples, N=120, also about 50 FFTs total;;  after FFT, the frequency interval always 6000/120=5000/100=50,  what change is bandwidth, from 2500Hz to 3000Hz。
if  I  measure longer, I indeed get more information about the signal, and I can plot spectrogram, but the resolution of frequency       
seems not change. (did I misunderstand the resolution definition?)

**Comment by versd** [comment]
The amount of FFT's that you do is up to you. Normally you have a fixed sample rate and you choose N yourself. Like 1024. The measuring time is then 1024 * T_sample. If you choose N to be 4096, then the measuring time is 4096 * T_sample.  With a N chosen to be 1024 you get a bin width of about sample_rate/1024 , if N = 4096 you get a bin width which is 4 times as small and thus more discernable and thus a higher resolution, assuming you keep the same sample_rate. ‘Resolution’ in this case refers to the bin width in Hz. 

The measuring time is not connected to the signals' period. Often the signal doesn't even have a discernable period in the first place! Therefore, we need windowing. It doesn’t make sense to change the sample_rate to accommodate for N. The sample_rate of a captured signal is fixed, it’s N that you change.

**Comment by chencjiajy** [comment]
Thank you! 
I now understand what you mean,  my mistake is thought when I do fft, I could only choose specific value, ie.`f_s/f_0`(where `f_s` is the sample rate and `f_0` is frequency of period signal), even after I finished read this chapter.
