### ISSUE TITLE
Not able to transmit and receive a sine wave using Python API (USRP B200) 

### ISSUE THREAD

**Issue by sreejith-tvs** [777arc/textbook#81]
I am trying to transmit and receive sine signal using USRP B200. I have referred the codes provided in the chapter 6 of pySDR. However I am not able to capture sine wave. The receive samples do not show any connection with the transmitted signal. I am copying the codes here.

########################

########################

import uhd
import numpy as np
import time as tim

usrp = uhd.usrp.MultiUSRP()

duration = 30 # seconds
center_freq = 900e6
sample_rate = 1e6
gain = 20 # [dB] start low then work your way up

## create sine wave
time = np.arange(0, duration, 1/sample_rate);# create sampling instances
samples = np.sin(time)

usrp.send_waveform(samples, duration, center_freq, sample_rate, [0], gain)

########################

########################
import uhd
import numpy as np
import matplotlib.pyplot as plt

usrp = uhd.usrp.MultiUSRP()
center_freq = 900e6 # Hz
sample_rate = 1e6 # Hz
gain = 10 # dB

usrp.set_rx_rate(sample_rate, 0)
usrp.set_rx_freq(uhd.libpyuhd.types.tune_request(center_freq), 0)
usrp.set_rx_gain(gain, 0)
usrp.set_rx_agc(True, 0)

## Set up the stream and receive buffer
st_args = uhd.usrp.StreamArgs("fc32", "sc16")
st_args.channels = [0]
metadata = uhd.types.RXMetadata()
streamer = usrp.get_rx_stream(st_args)
recv_buffer = np.zeros((1, 1000), dtype=np.complex64)

## Start Stream
stream_cmd = uhd.types.StreamCMD(uhd.types.StreamMode.start_cont)
stream_cmd.stream_now = True
streamer.issue_stream_cmd(stream_cmd)

duration = 20 # seconds
t_n = np.arange(0, duration, 1/sample_rate);# time axis
num_samps=len(t_n)

## Receive Samples
samples = np.zeros(num_samps, dtype=np.complex64)
for i in range(num_samps//1000):
streamer.recv(recv_buffer, metadata)
data=recv_buffer[0]
samples[i*1000:(i+1)*1000] = data

## Stop Stream
stream_cmd = uhd.types.StreamCMD(uhd.types.StreamMode.stop_cont)
streamer.issue_stream_cmd(stream_cmd)

print(len(samples))
print(samples[0:10])
plt.plot(t_n, np.real(samples),'')
plt.show()

**Comment by 777arc** [comment]
Do you have the tx and rx ports connected?  And if so, is there an attenuator between them?  If there's an attenuator then you'll definitely have to increase the gain, where it says "start low then work your way up".

**Comment by sreejith-tvs** [comment]
Thank you. It's working when I change the gain.
