### ISSUE TITLE
Grammar in Chapter 2

### ISSUE THREAD

**Issue by snethej** [777arc/textbook#83]
In frequency_domain.rst, there is a sentence:

> If the input is complex, the negative and positive portions will be different, but if **it real** then they will be identical.

which needs an "is" (or changed to "it's" if conjuctions are okay) for proper grammar.  It could also need a comma after "real" but commas are a little more up-in-the-air in writing these days.

**Comment by 777arc** [comment]
ah nice catch, ill fix it
