### ISSUE TITLE
TikZ image not rendering on Frequency Domain Page.

### ISSUE THREAD

**Issue by Dygear** [777arc/textbook#86]
This commit 6630838 has a regression for the [content/frequency_domain.rst](https://github.com/777arc/textbook/issues/new#diff-89216b3ab7f4190db3066c982d0b9487ac58e95bd961cb90c71123d23d84f470) page. Line 202 - 213 has a TikZ format that doesn't appear to be parsing and rendering.

The Ukraine version also has the bug, the nl version seems to be correct, the fr version is using the older `svg` file.

**Comment by 777arc** [comment]
Nice catch!  Looks like it had to do with the comment on the line prior to the tikz, fixing now
