### ISSUE TITLE
Differential coding

### ISSUE THREAD

**Issue by sei-jgwohlbier** [777arc/textbook#87]
![image](https://github.com/777arc/textbook/assets/125931866/bf217ad3-a3ff-4fe9-b3b4-c09f16a235be)

If the first bit of the second sequence represents the reference bit (assuming so since the first sequence has 7 bits and the second has 8 bits) I think it should be
```
x1100010
10010011
```
If you concur I can submit a PR.

**Comment by 777arc** [comment]
From the way I've seen it in textbooks, you compare it like the following, and if they are equal then the next bit is a 0, if they are different the next bit is a 1.  So the resulting bits (2nd line) would be 10111100

![image](https://github.com/777arc/textbook/assets/5722532/0fb36edc-6de8-42a2-94a5-0ac8339a1ee8)

Although I'm now realizing the diagram doesnt match the example which isnt great, I'll have to fix that

**Comment by sei-jgwohlbier** [comment]
It's unclear to me how you're initiating the sequence, I guess? Is the "reference bit" shown in the first line? If it is, then the second bit should be 0 since 1 follows a 1. If it is not and a reference 1 is implied, then it should be 0 since 1 follows a 1.

In any event, we might be able to improve the explanation that has resulted in my misunderstanding.

**Comment by 777arc** [comment]
Yes now that I look at it again, I don't really explain how to do it, I just show the example.  So the wikipedia page  https://en.wikipedia.org/wiki/Differential_coding explains it with the equation 

![image](https://github.com/777arc/textbook/assets/5722532/ca875a3a-8b56-470d-ad8b-59b68603a671)

ie you compare the current input bit with the prev output bit (hence the need to start the output with an arbitrary 1 or 0) to get the current output bit.  "Compare" meaning an XOR operation, or as wikipedia says a binary addition (output is 0 if they match, 1 if they are different).  

I also don't really get into the decoding part, which would make it more clear that you recover the original bits based on the difference between the symbols and not their actual values, as wikipedia mentions.  That's also why it doesnt matter whether you start with a 1 or 0 when encoding.  

Would you be interested in improving that subsection?  If not I'll give it a go.

**Comment by sei-jgwohlbier** [comment]
I'm happy to try to improve it.

It's still not clear to me, though, why the first encoded bit isn't 0. The text states "Assume we start the output sequence with 1;" The first bit you propose to encode from `[1100010]` is a 1, so the result of the xor should be 0. 

ooooohhhh .... should I be reading right to left instead of left to right?

**Comment by sei-jgwohlbier** [comment]
ok, I think I was mixing my inputs. I was doing diffs on consecutive input symbols rather than the diffing the input with the previously encoded symbol. I'll take a shot at making it more clear.

**Comment by sei-jgwohlbier** [comment]
I've got a PR ready, but have a question. My editor removes trailing white space from lines, so there are several diffs in the file rather than just the straight up text diff. Is that Ok, or do you want me to preserve the trailing spaces?

e.g., from `git diff -R`

<img width="727" alt="image" src="https://github.com/777arc/textbook/assets/125931866/f51806f2-3b3b-4b63-96ad-27ffe35a340b">

**Comment by 777arc** [comment]
I can fix that on my end

**Comment by 777arc** [comment]
Oh actually that's a good cleanup to have anyway so we can leave them in
